#!/usr/bin/env python3
"""
FINAL RENDERER - JB APUL v3
Merges audio + video into final output, creates media_items record.

FIX: Atomic safety — DB commit BEFORE file move.
FIX: Proper error messages with actual exception details.
FIX: Populate audio_duration column.
"""

import os
import sys
import subprocess
import traceback

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from db import get_db, update_progress, append_log

FFMPEG = "ffmpeg"
FFPROBE = "ffprobe"


def get_duration(path: str) -> float:
    """Get media duration in seconds."""
    try:
        r = subprocess.run(
            [FFPROBE, "-v", "error", "-show_entries", "format=duration",
             "-of", "default=noprint_wrappers=1:nokey=1", path],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, timeout=30,
        )
        return float((r.stdout or "").strip())
    except Exception:
        return 0.0


def run_ffmpeg(cmd: list):
    """Run FFmpeg command, raise on failure."""
    p = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    if p.returncode != 0:
        raise RuntimeError(f"FFmpeg failed (rc={p.returncode}): {(p.stdout or '')[-500:]}")


def cleanup_tmp(tmp_dir: str, job_id: int):
    """Remove temp files for this job."""
    try:
        job_id_str = str(job_id)
        for filename in os.listdir(tmp_dir):
            tmp_path = os.path.join(tmp_dir, filename)
            if not os.path.isfile(tmp_path):
                continue
            if any(filename.endswith(suffix) for suffix in [f"_{job_id_str}.mp4", f"_{job_id_str}.wav"]):
                os.remove(tmp_path)
            elif filename.startswith(f"_mp3_merge_{job_id_str}"):
                os.remove(tmp_path)
    except Exception as exc:
        append_log(job_id, f"Cleanup warning: {exc}")
        print(f"[FINAL] Cleanup warning: {exc}")


def main():
    if len(sys.argv) != 3:
        print("[FINAL] Usage: final_renderer.py <job_id> <storage_path>")
        sys.exit(1)

    job_id = int(sys.argv[1])
    storage_path = sys.argv[2]
    tmp_dir = os.path.join(storage_path, "tmp")
    assets = os.path.join(storage_path, "assets")
    os.makedirs(tmp_dir, exist_ok=True)

    conn = None
    temp_output = None

    try:
        # Load job
        conn = get_db()
        cur = conn.cursor()
        cur.execute("SELECT * FROM production_jobs WHERE id=%s", (job_id,))
        job = cur.fetchone()

        if not job:
            append_log(job_id, f"Job {job_id} not found")
            print(f"[FINAL] Job {job_id} not found")
            sys.exit(1)

        update_progress(job_id, 5, "Final: memuat job")
        append_log(job_id, "Final: memuat job")
        print(f"[FINAL] Final: memuat job")

        if job["final_status"] == "done":
            append_log(job_id, f"Job {job_id} already done, skip")
            print(f"[FINAL] Job {job_id} already done, skip")
            sys.exit(0)

        if job["audio_status"] != "done" or job["video_status"] != "done":
            append_log(job_id, f"Audio/video not ready for job {job_id}")
            print(f"[FINAL] Audio/video not ready for job {job_id}")
            sys.exit(1)

        video_path = job["video_path"]
        audio_path = job["audio_path"]
        channel_id = int(job["channel_id"] or 0)

        # Always use output_filename from job (generated by API)
        final_name = (job["output_filename"] or "").strip()
        
        # Fallback: generate from video source if output_filename is empty
        if not final_name:
            original_video_name = os.path.basename(video_path) if video_path else ""
            if original_video_name:
                final_name = f"final_{original_video_name}"

        if channel_id <= 0:
            append_log(job_id, f"Invalid channel_id for job {job_id}")
            print(f"[FINAL] Invalid channel_id for job {job_id}")
            sys.exit(1)

        if not final_name:
            append_log(job_id, f"output_filename empty for job {job_id}")
            print(f"[FINAL] output_filename empty for job {job_id}")
            sys.exit(1)

        if not video_path or not os.path.exists(video_path):
            append_log(job_id, f"Invalid video_path: {video_path}")
            print(f"[FINAL] Invalid video_path: {video_path}")
            sys.exit(1)

        if not audio_path or not os.path.exists(audio_path):
            append_log(job_id, f"Invalid audio_path: {audio_path}")
            print(f"[FINAL] Invalid audio_path: {audio_path}")
            sys.exit(1)

        # Output directory
        upload_ready_dir = os.path.join(assets, "upload_ready", str(channel_id))
        os.makedirs(upload_ready_dir, exist_ok=True)

        append_log(job_id, f"Video: {os.path.basename(video_path)} | Audio: {os.path.basename(audio_path)}")

        print(f"[FINAL] Video: {os.path.basename(video_path)} | Audio: {os.path.basename(audio_path)}")
        append_log(job_id, f"Output: {final_name}")
        print(f"[FINAL] Output: {final_name}")
        update_progress(job_id, 20, "Final: menggabung audio+video")
        append_log(job_id, "Final: menggabung audio+video")
        print(f"[FINAL] Final: menggabung audio+video")

        temp_output = os.path.join(tmp_dir, f"final_{job_id}.mp4")
        final_path = os.path.join(upload_ready_dir, final_name)
        relative_path = f"assets/upload_ready/{channel_id}/{final_name}"

        # Step 1: FFmpeg merge audio + video -> temp file
        run_ffmpeg([
            FFMPEG, "-y",
            "-i", video_path,
            "-i", audio_path,
            "-map", "0:v:0",
            "-map", "1:a:0",
            "-c:v", "copy",
            "-c:a", "aac", "-b:a", "192k",
            "-shortest",
            temp_output,
        ])

        if not os.path.exists(temp_output) or os.path.getsize(temp_output) < 1024:
            append_log(job_id, f"FFmpeg output invalid: {temp_output}")
            print(f"[FINAL] FFmpeg output invalid: {temp_output}")
            sys.exit(1)

        tmp_size = os.path.getsize(temp_output) / (1024*1024)
        append_log(job_id, f"Merge done ({tmp_size:.1f}MB), menghitung durasi...")
        print(f"[FINAL] Merge done ({tmp_size:.1f}MB), menghitung durasi...")
        update_progress(job_id, 60, "Final: menghitung durasi")
        append_log(job_id, "Final: menghitung durasi")
        print(f"[FINAL] Final: menghitung durasi")

        # Step 2: Get audio duration for the record
        audio_duration = int(get_duration(temp_output))

        update_progress(job_id, 70, "Final: menyimpan record database")
        append_log(job_id, "Final: menyimpan record database")
        print(f"[FINAL] Final: menyimpan record database")

        # Step 3: DB operations FIRST (before moving file)
        size_bytes = int(os.path.getsize(temp_output))

        cur.execute("""
            SELECT id FROM media_items
            WHERE channel_id=%s AND asset_type='upload_ready' AND filename=%s
            LIMIT 1
        """, (channel_id, final_name))
        existing = cur.fetchone()

        if existing:
            cur.execute("""
                UPDATE media_items
                SET file_path=%s, file_size=%s, updated_at=NOW()
                WHERE id=%s
            """, (relative_path, size_bytes, existing["id"]))
            media_id = existing["id"]
        else:
            cur.execute("""
                INSERT INTO media_items (channel_id, filename, file_path, asset_type, file_size, created_at)
                VALUES (%s, %s, %s, 'upload_ready', %s, NOW())
                RETURNING id
            """, (channel_id, final_name, relative_path, size_bytes))
            media_id = cur.fetchone()["id"]

        # Mark job done (DB commit BEFORE file move)
        cur.execute("""
            UPDATE production_jobs
            SET status='done', final_status='done', final_path=%s,
                progress=90, audio_duration=%s, updated_at=NOW()
            WHERE id=%s
        """, (final_path, audio_duration, job_id))
        conn.commit()

        update_progress(job_id, 90, "Final: memindahkan file")
        append_log(job_id, "Final: memindahkan file")
        print(f"[FINAL] Final: memindahkan file")

        # Step 4: Move temp -> final (AFTER DB commit)
        if os.path.exists(final_path):
            os.remove(final_path)
        os.replace(temp_output, final_path)
        temp_output = None  # Mark as moved, don't cleanup

        # Final progress update
        update_progress(job_id, 100, "Final: selesai")
        append_log(job_id, "Final: selesai")
        print(f"[FINAL] Final: selesai")

        # Cleanup remaining temp files
        cleanup_tmp(tmp_dir, job_id)

        append_log(job_id, f"Final saved to: {final_path}")

        print(f"[FINAL] Final saved to: {final_path}")
        final_size = os.path.getsize(final_path) / (1024*1024)
        append_log(job_id, f"Saved: {final_name} ({final_size:.1f}MB, {audio_duration}s)")
        print(f"[FINAL] Saved: {final_name} ({final_size:.1f}MB, {audio_duration}s)")
        append_log(job_id, f"Job {job_id} DONE (media_id={media_id})")
        print(f"[FINAL] Job {job_id} DONE (media_id={media_id})")

    except Exception as exc:
        error_detail = f"Final renderer: {str(exc)[:200]}"
        append_log(job_id, f"ERROR: {error_detail}")
        print(f"[FINAL] ERROR: {error_detail}")
        append_log(job_id, f"TRACEBACK: {traceback.format_exc()}")
        print(f"[FINAL] TRACEBACK: {traceback.format_exc()}")
        # Update job with specific error
        try:
            if conn and not conn.closed:
                cur = conn.cursor()
                cur.execute("""
                    UPDATE production_jobs
                    SET status='failed', final_status='failed',
                        error_message=%s, updated_at=NOW()
                    WHERE id=%s
                """, (error_detail, job_id))
                conn.commit()
        except Exception:
            pass
        sys.exit(1)

    finally:
        # Cleanup temp file if still exists (FFmpeg succeeded but DB/move failed)
        if temp_output and os.path.exists(temp_output):
            try:
                os.remove(temp_output)
            except Exception:
                pass
        if conn and not conn.closed:
            conn.close()


if __name__ == "__main__":
    main()
